==  Day 9: Rope Bridge  ==

This solution is written in Kotlin.

The original puzzle can be found at https://adventofcode.com/2022/day/9

The solution uses for both parts of the puzzle function _RopeBridge_. Here the puzzle input is parsed and the path of the rope's head is calculated and stored in first list of lists. For all following segments it's path is calculated by calling function _follow_ using the coordinates of the segment one before. The path for all segments is stored in a list of lists.

function _RopeBrigde_
[source, kotlin, numbered]
....
include::day2209_1_2.kt[tags=ropeBridge]
....

function _follow_
[source, kotlin, numbered]
....
include::day2209_1_2.kt[tags=follow]
....

=== First Star

How does it work: +

After calculating the path of all segments the path of the first segment will be stripped of all positions visited more than once and than the remaining positions counted.

=== Second Star

How does it work: +

After calculating the path of all segments the path of the last segment (#9) will be stripped of all positions visited more than once and than the remaining positions counted.

At the end, both solutions are printed out. 
[source, kotlin, numbered]
....
include::day2209_1_2.kt[tags=output]
....
