==  Day 1: Calorie Counting  ==

This solution is written in Kotlin.

The original puzzle can be found at https://adventofcode.com/2022/day/1


=== First Star

How does it work: +

Inside function _calories_ the puzzle input is read and accumulated. Whenever a new block comes, the accumulated value is added to a list and the accumulation starts from new. The function takes one input parameter, if it is _1_ only the max value of the list with accumulated calories is returned
[source, kotlin, numbered]
....
include::day2201_1_2.kt[tags=calories]
....


=== Second Star

How does it work: +

The same function call is used only with a different input parameter and therefore not the max value is returned but the sum of the three highest values
[source, kotlin, numbered]
....
include::day2201_1_2.kt[tags=calories]
....

At the end, both solutions are printed out. 
[source, kotlin, numbered]
....
include::day2201_1_2.kt[tags=output]
....


=== Add on

Since today I had some free time, I tried to find another solution with only one line. There was still some trouble with using readText, I guess there is still some missmatch with the charset, I used readLines instead which is not as elegant, but for the time being I need to get back to some other stuff.
[source, kotlin, numbered]
....
include::day2201_1_2.kt[tags=oneliner]
....
