== Day 03: Rucksack Reorganization ==

This is my implementation for both rounds of the rucksack reorganization puzzle.
This year, I am using Rust to solve the challenges.
My first priority is learning more about the language, while the creation of
easily readable code is a second priority, this time.
Wiriting fast code is a far-away third priority.

=== Oveview ===

All source code lives in the `src` directory.
This solution contains a `main.rs`, which defines the main executable.
There is also a `data.rs`, which specifies data types important for this
solution as well as associated functions, methods, and traits.
There is also an `io.rs`, which contains helper functions related to input
parsing and output processing.

=== Solution ===

This one was straightforward, but I am not too happy with how the solution
looks.
Working with the `HashSet` type was not as easy as I thought, e.g. when trying
to compute the overlap of multiple sets.
Furthermore, I somehow misunderstood part 2 at first, which lead me on a wild
goose chase.
Still, this works, but I lack the time to provid more details about the
implementation.

`main.rs`
[source,rust,numbered]
----
include::src/main.rs[tags=main]
----

`data.rs`
[source,rust,numbered]
----
include::src/data.rs[tags=data]
----

There are currently no tests.

=== How to run ===

Please have a look at `src/main.rs` for expeced names of input files.
Assuming the expected files are present, you only need to execute `cargo run` to
run the solution.
The expected input files are ususally called `sample.dat` and `stage_1.dat`.
