== Day 05: Supply Stacks ==

This is my implementation for both rounds of the supply stacks puzzle.
This year, I am using Rust to solve the challenges.
My first priority is learning more about the language, while the creation of
easily readable code is a second priority, this time.
Wiriting fast code is a far-away third priority.

=== Overview ===

All source code lives in the `src` directory.
This solution contains a `main.rs`, which defines the main executable.
There is also a `data.rs`, which specifies data types important for this
solution as well as associated functions, methods, and traits.
There is also an `io.rs`, which contains helper functions related to input
parsing and output processing.

=== Solution ===

Once the inputs have been parsed, this one was straightforward to solve.
You simply have to follow the instructions.
Solving part 2 was particulary nice as I could just pass in a different crate
movement function.
I took the lazy approach for part 2 and implemented it via a temporary stack as
intermediary.

Parsing the stacks was a bit harder, on the other hand, because there was no
separator string in place that would make it possible to easily distinguish the
different stacks.
I was tempted to preprocess the input via a shell script or even manually, which
would have simplified parsing.
But then I realised that a filter function each could be used to extract all the
lines belonging to either the stack definition or the definition of movement
instructions.
The use of inexact chunking then made it possible to easily read in the
different stacks.

Note that I have used two types to represent stacks: `Vec<StackLine>`, which is
the type representing the stack input, and `Vec<Stack>`, which is basically the
transpose of the first type.
Maybe using an actual matrix would have been a beter idea, but this works, too.

I noted that many of the terms used in this challenge are reserved words in rust
such as "crate" or "move".

`main.rs`
[source,rust,numbered]
----
include::src/main.rs[tags=main]
----

`data.rs`
[source,rust,numbered]
----
include::src/data.rs[tags=data]
----

`io.rs`
[source,rust,numbered]
----
include::src/io.rs[tags=io]
----

There are currently no tests.

=== How to run ===

Please have a look at `src/main.rs` for expeced names of input files.
Assuming the expected files are present, you only need to execute `cargo run` to
run the solution.
The expected input files are ususally called `sample.dat` and `stage_1.dat`.
