== Day 11: Monkey in the Middle ==

https://rust-lang.org[Rust] solution to https://adventofcode.com/2022/day/11[AoC|2022|11].

It was quite tedious today for me to create the solution.

I liked the twist in part 2. Since each monkey does a modulo `test` before passing on the item, we can safely do a modulo with the product of all tests of all monkeys to keep the numbers small. Still took me a while to complete part two because I just replaced the `/ 3` from the first part with `/ mod` in the second part which is obviously not the same as `% mod`. And I have to confess that my first attempt was to use 128bit numbers.

=== Input ===

Parsing was a pain today. I almost regret my decision to not use external dependencies (and thus not use Regex) ...

[source,rust,numbered]
----
include::src/lib.rs[tags=input]
----

=== Solution ===

Here is my solution for both parts. The `solve` function is called with `div = 3` for the first part and `div = 1` for the second.

[source,rust,numbered]
----
include::src/lib.rs[tags=solution]
----

=== Tests ===

... and the tests

[source,rust,numbered]
----
include::src/lib.rs[tags=tests]
----
