== Day 21: Monkey Math ==

This is my implementation for both rounds of today's puzzle.
This year, I am using Rust to solve the challenges.
My first priority is learning more about the language, while the creation of
easily readable code is a second priority, this time.
Wiriting fast code is a far-away third priority.

=== Oveview ===

All source code lives in the `src` directory.
This solution contains a `main.rs`, which defines the main executable.
There is also a `data.rs`, which specifies data types important for this
solution as well as associated functions, methods, and traits.
There is also an `io.rs`, which contains helper functions related to input
parsing and output processing.

=== Solution ===

No time to explain, barely enough time to implement.

Part 1 is straightforward, simply fill in all monkey values that you can each
round until you found the value for `root`.

Part 2 was more tricky.
Looking at the data, it becomes clear that only one side of the equation depends
on the human's value while the other one is constant.
My code determines that side automatically.

Furthermore, you need to realise that the value of the other side changes
monotonically depending on the human's value.
Then, it's a simple search over the available parameter space.
I opted for a search with more steps than a binary search and it works well
enough for my inputs.
I also assume that the number we need to shout is positive since all monkeys
shout positive values themselves.
That might not hold for all inputs.

My solytion might not work for all inputs but it should be easy to fix.
I added some checks that panic if they fail in orer to catch edge cases but
those didn't occur for me.

`main.rs`
[source,rust,numbered]
----
include::src/main.rs[tags=main]
----

`data.rs`
[source,rust,numbered]
----
include::src/data.rs[tags=data]
----

There are no tests this time.

=== How to run ===

Please have a look at `src/main.rs` for expeced names of input files.
Assuming the expected files are present, you only need to execute `cargo run` to
run the solution.
The expected input files are ususally called `sample.dat` and `stage_1.dat`.
