
Day 13 of year 2022
https://adventofcode.com/2022/day/13

== What I learned

. Mostly it was a pain to figure out the right parsing. And I also used bubble sort, which I learned way back in the 80's. (It's not the best, but it's easy to understand).

== Approach

. I parse through each line using a function called parse_line. If you find a list somewhere as an entry, you find the closing ] and push that string into parse_line. Otherwise, it's fairly straightforward. At the end, I have a list of lists that correspond to the strings in the input file.

**Star 1** +

. I made a function called compare_signals. For each of the cases, I created the logic. If you are comparing lists instead of digits, you call compare_signals again. We return as soon as we have a True or False. Then I just do the math as defined in the problem statement.

**Star 2** +

. I add the 2 new packets to my list. And then just run bubble sort using my compare_signals function. I used bubble sort because I could 1-1 reuse my function and it's also easy to understand. The performance isn't an issue with such a sort list.

== Run script
Run the solution with `python solution.py`

[source, python]
....
include::solution.py[]
....