== Treetop Tree House

Today's puzzle was all about creating a grid and determining the state of coordinates given certain conditions.

=== Model

I decided to create a class to represent the grid as an array of int array.

[source,kotlin]
....
class Grid(val lines: Array<IntArray>) {
    fun width() = lines[0].size
    fun height() = lines.size
    fun get(x: Int, y: Int) = lines[x][y]
}
....

=== Parsing

The data was presents as lines of digits, each digits represented a tree and the value was the height of the tree.

[source,text]
....
30373
25512
65332
33549
35390
....

Parsing meant converting each line to an array of int by converting each character to it's integer representation.

[source,kotlin]
....
fun parseGrid(input: List<String>): Grid {
  return Grid(input.map { line -> line.toList().map { it - '0' }.toIntArray() }.toTypedArray())
}
....

=== Part 1

We had to determine how many trees are visible considering it is invisible it there is a tree of similar or greater height above or below, to the left or right.

I added a visible method to Grid

[source,kotlin]
....
fun visible(x: Int, y: Int): Boolean {
  val treeHeight = get(x, y)
  var bottom = true
  var top = true
  var left = true
  var right = true
  for (i in 0 until x) {
    val tree = get(i, y)
    if (tree >= treeHeight) {
      top = false
      break
    }
  }
  for (i in x + 1 until height()) {
   if (get(i, y) >= treeHeight) {
      bottom = false
      break
    }
  }
 for (i in y + 1 until width()) {
   if (get(x, i) >= treeHeight) {
      right = false
      break
    }
  }
  for (i in 0 until y) {
    if (get(x, i) >= treeHeight) {
      left = false
      break
    }
  }
  return top || bottom || left || right
}

fun calcVisible(grid: Grid): Int {
  val height = grid.height()
  val width = grid.width()
  var result = (height * 2) + (width * 2) - 4
  for (x in 1 until height - 1) {
    for (y in 1 until width - 1) {
      if (grid.visible(x, y)) {
        result += 1
      }
    }
  }
  return result
}
....

=== Part 2

We had to calculate a scenic value for each tree and determine the answer was maximum scenic.
The scenic value was determined by how many trees were visible from a given tree.

I added a scenic method to Grid.

[source,kotlin]
....
fun scenic(x: Int, y: Int): Int {
  val treeHeight = get(x, y)
  var bottom = 0
  var top = 0
  var left = 0
  var right = 0
  for (i in x + 1 until height()) {
    bottom += 1
    if (get(i, y) >= treeHeight) {
      break
    }
  }
  for (i in x - 1 downTo  0 ) {
    top += 1
    if (get(i, y) >= treeHeight) {
      break
    }
  }
  for (i in y + 1 until width()) {
    right += 1
    if (get(x, i) >= treeHeight) {
      break
    }
  }
  for (i in y - 1 downTo  0 ) {
    left += 1
    if (get(x, i) >= treeHeight) {
      break
    }
  }
  return bottom * left * right * top
}

fun calcMaxScenic(grid: Grid): Int {
  val height = grid.height()
  val width = grid.width()
  var result = 0
  for (x in 1 until height - 1) {
    for (y in 1 until width - 1) {
      result = max(result, grid.scenic(x, y))
    }
  }
  return result
}
....

=== Full source
[source,kotlin]
....
include::src/solution.kt[]
....
