== Rope Bridge

Today's puzzle was about simulating the movement of a rope or chain. The knots / links follow each other when the head is pulled in a direction. The simulation had to implement rules for the movement and record the movement of the tail and reporting the number of unique positions visited by the tail.

In part 1 the rope has 2 knots and in part 2 the rope had 10 knots.

=== Model

I decided to model the `Rope` as an array of `Position`

[source,kotlin]
....
data class Position(val row: Int, val col: Int) {
  fun left() = Position(row, col - 1)
  fun right() = Position(row, col + 1)
  fun above() = Position(row - 1, col)
  fun below() = Position(row + 1, col)
  fun distance(pos: Position): Int = max(abs(pos.row - row), abs(pos.col - col))
  operator fun minus(pos: Position) = Position(row - pos.row, col - pos.col)
  operator fun plus(pos: Position) = Position(row + pos.row, col + pos.col)
  fun sign(): Position = Position(row.sign,col.sign)
  fun move(direction: Char): Position {
    return when (direction) {
      'U' -> above()
      'D' -> below()
      'L' -> left()
      'R' -> right()
      else -> error("Expected one of U,D,L,R not ${direction}")
    }
  }
  override fun toString(): String {
    return "(col=$col, row=$row)"
  }
}

class Rope(val knots: Array<Position>) {
  val head: Position
    get() = knots[0]
  val tail: Position
    get() = knots[knots.lastIndex]

  operator fun set(index: Int, pos: Position) { knots[index] = pos }

  operator fun get(index: Int) = knots[index]
  fun indexOf(pos: Position) = knots.indexOf(pos)
  override fun toString() = knots.contentToString()
}
....

=== Parsing

The input was a list of steps with the direction as one of `U`,`D`,`L`,`R` and a number for the distance moved.

[source,kotlin]
....
data class Step(val direction: Char, val distance: Int)

fun parseSteps(input: List<String>): List<Step> {
  return input.map {
    val words = it.split(" ")
    Step(words[0][0], words[1].toInt())
  }
}
....

=== Simulating the rope

After when I got to part 2 I had a situation where my answer to the provided data was correct but AOC report my answer with the input as low. I tried to find a case where I wasn't handling the tail correctly. All this back and forth lead me to simplifying the calculation to the point where I calculated the difference between the knots and the movement was then a step in the direction of the first knot and it could be diagonally if the difference had values in both axis.

This worked and was a lot simpler. When I looked at some other submissions in the Kotlin community I discovered `Int.sign()` which returns `0`,`1` or `-1` depending in the value. I added operators to `Position` for `-` and `+` and a `sign` method. This reduced the final expression to a very simple one.

[source,kotlin]
....
for (index in 1 until knots) {
  val prev = rope[index - 1]                      // <1>
  val next = rope[index]                          // <2>
  if (prev != next && prev.distance(next) > 1) {  // <3>
    val diff = prev - next                        // <4>
    rope[index] = next + diff.sign()              // <5>
  }
}
....
<1> The previous knot
<2> The knot we want to move
<3> If they aren't in same location and the https://en.wikipedia.org/wiki/Chebyshev_distance[Chebyshev] distance is more than 1.
<4> Determine the difference between the positions
<5> Add the sign of the difference to the knot we want to move

[source,kotlin]
....
fun calcVisits(steps: List<Step>, knots: Int, printStep: Boolean): Int {
  val rope = Rope(Array(knots) { Position(0, 0) })
  val start = rope.head
  val visited = mutableSetOf<Position>()
  visited.add(rope.tail)
  steps.forEach { step ->
    for (i in 0 until step.distance) {
      rope[0] = rope.head.move(step.direction)
      for (index in 1 until knots) {
        val prev = rope[index - 1]
        val next = rope[index]
        if (prev != next && prev.distance(next) > 1) {
          val diff = prev - next
          rope[index] = next + diff.sign()
        }
      }
      visited.add(rope.tail)
      if (printStep) {
        println()
        print(steps, visited, start, rope, knots, false)
      }
    }
  }
  println()
  print(steps, visited, start, rope, knots, true)
  return visited.size
}
....

=== Full source
[source,kotlin]
....
include::src/solution.kt[]
....
