== Day 19: Not Enough Minerals ==

This is my implementation for both rounds of today's puzzle.
This year, I am using Rust to solve the challenges.
My first priority is learning more about the language, while the creation of
easily readable code is a second priority, this time.
Wiriting fast code is a far-away third priority.

=== Oveview ===

All source code lives in the `src` directory.
This solution contains a `main.rs`, which defines the main executable.
There is also a `data.rs`, which specifies data types important for this
solution as well as associated functions, methods, and traits.
There is also an `io.rs`, which contains helper functions related to input
parsing and output processing.

=== Solution ===

Today, I first went on a wild goose chase because I had a fancy idea, which
totally didn't work out but cost quite a bit of time.
My second attempt was thus a straightforward implementation of the instructions
with a cache because state values often reapeat themselves.
The cache associates each world state with its best geode value.
Note that a state includes the remaining simulation time.
Thus, if we find a value that's in the cache, we can avoid go compute the same
world progression again because the state uniquely identifies how the world will
progress from that point on.

In my input for part 1, there was one blueprint that didn't work out with a
straightforward implementation of the cache.
That is, the cache grew so large that my computer ran out of RAM.
Thus, I only cached values until some time steps before the end.

`main.rs`
[source,rust,numbered]
----
include::src/main.rs[tags=main]
----

`data.rs`
[source,rust,numbered]
----
include::src/data.rs[tags=data]
----

There are no tests this time.

=== How to run ===

Please have a look at `src/main.rs` for expeced names of input files.
Assuming the expected files are present, you only need to execute `cargo run` to
run the solution.
The expected input files are ususally called `sample.dat` and `stage_1.dat`.
