== Day 15: Beacon Exclusion Zone ==

This is my implementation for both rounds of today's puzzle.
This year, I am using Rust to solve the challenges.
My first priority is learning more about the language, while the creation of
easily readable code is a second priority, this time.
Wiriting fast code is a far-away third priority.

=== Oveview ===

All source code lives in the `src` directory.
This solution contains a `main.rs`, which defines the main executable.
There is also a `data.rs`, which specifies data types important for this
solution as well as associated functions, methods, and traits.
There is also an `io.rs`, which contains helper functions related to input
parsing and output processing.

=== Solution ===

Part 1 was easy enough, I simply gave each exclusion zone a function that
provided all points within it at a certain y-coordinate, fed all of them into a
set, and then checked how many elements it had.
Not very pretty but worked well enough.

At first, I brute-forced part 2 and got lucky.
However, that solution wasn't satisfying and then I found some more time to look
into this today.
Yeah!

The final solution to part 2 turned out to be one that I never expected to
perform well but that did, as it turns out.
What I do is I basically perform a line scan along the x axis for all y
coordinates.
For each y, I extract all non-empty overlaps between exclusion zones and the
scanning line and discarded those that were outside the playing field.
Then, I merged those overlaps.

To make merging overlaps, which are ranges, very easy, I sorted all of then
first by their x_min coordinate and, if those are equal, by their x_max
coordinate.
I never thought that sorting them would be efficient enough, but it is.
Once they have been sorted, merging them is easy.
If x_min of the first entry is not 0, we've found the coordinates.
Otherwise, we check whether x_min of the next range in line is greater than the
current x_max.
If so, we've found the empty spot.
If not, we increase our currently known x_max to the x_max of that range.
Rinse repeat for every y until the distress beacon has been found.

`main.rs`
[source,rust,numbered]
----
include::src/main.rs[tags=main]
----

`data.rs`
[source,rust,numbered]
----
include::src/data.rs[tags=data]
----

There are no tests this time.

=== How to run ===

Please have a look at `src/main.rs` for expeced names of input files.
Assuming the expected files are present, you only need to execute the command
`cargo run --release` to run the solution.
The expected input files are ususally called `sample.dat` and `stage_1.dat`.
