== Day 09: Rope Bridge ==

This is my implementation for both rounds of this day's puzzle.
This year, I am using Rust to solve the challenges.
My first priority is learning more about the language, while the creation of
easily readable code is a second priority, this time.
Wiriting fast code is a far-away third priority.

=== Oveview ===

All source code lives in the `src` directory.
This solution contains a `main.rs`, which defines the main executable.
There is also a `data.rs`, which specifies data types important for this
solution as well as associated functions, methods, and traits.
There is also an `io.rs`, which contains helper functions related to input
parsing and output processing.

=== Solution ===

Solving this was quite a bit of fun!

I created a `Vec` class to represent 2d vectors and was quite happy to have
outsourced a lot of the logic into that class.
For example, the class offers a `mv` method, which only ever lets it move by one
space, which is a safeguard against trying to move too far at once.
I haven't tried moving by more than one space at a time because it seemed overly
complicated.

Furthermore, the custom `Vec` class has an `iter` method that provides an
iterator over unit-size steps (unit vectors in the sense of the manhattan
metric) that, if followed, ensure the same distance has been traveled as
described by the original vector.
That way, a simple iteration over iterators gave us all the steps we needed.

For solving part 2, one problem was borrowing two elements of the rope
simultaneously while one was even borrowed mutably.
That won't work in rust.
Instead, I use a temporary variable to keep track of the updated position of the
previous knot in the rope.

I've also played around with lifetimes a bit.

`main.rs`
[source,rust,numbered]
----
include::src/main.rs[tags=main]
----

`data.rs`
[source,rust,numbered]
----
include::src/data.rs[tags=data]
----

There are no tests this time.

=== How to run ===

Please have a look at `src/main.rs` for expeced names of input files.
Assuming the expected files are present, you only need to execute `cargo run` to
run the solution.
The expected input files are ususally called `sample.dat` and `stage_1.dat`.
