== Day 12: Hill Climbing Algorithm ==

This is my implementation for both rounds of today's puzzle.
This year, I am using Rust to solve the challenges.
My first priority is learning more about the language, while the creation of
easily readable code is a second priority, this time.
Wiriting fast code is a far-away third priority.

=== Oveview ===

All source code lives in the `src` directory.
This solution contains a `main.rs`, which defines the main executable.
There is also a `data.rs`, which specifies data types important for this
solution as well as associated functions, methods, and traits.
There is also an `io.rs`, which contains helper functions related to input
parsing and output processing.

=== Solution ===

No time to write much.
This might be the most complex puzzle this year so far.

Part 1 can be solved by implementing `A*` on a directed acyclic graph where each
step has unit cost.
Then, have it search for the path from start to finish, making sure to have a
sane heuristic.

With a directed acyclic graph, part 2 can be solved very easily by adding a new,
virtual node and connecting it to all nodes of height `a`.
Then, search for the shortest path from that virtual node to the end and
subtract 1 from the length of the path (the virtual node).

`main.rs`
[source,rust,numbered]
----
include::src/main.rs[tags=main]
----

`data.rs`
[source,rust,numbered]
----
include::src/data.rs[tags=data]
----

There are no tests this time.

=== How to run ===

Please have a look at `src/main.rs` for expeced names of input files.
Assuming the expected files are present, you only need to execute `cargo run` to
run the solution.
The expected input files are ususally called `sample.dat` and `stage_1.dat`.
