== Day 13: Distress Signal ==

This is my implementation for both rounds of today's puzzle.
This year, I am using Rust to solve the challenges.
My first priority is learning more about the language, while the creation of
easily readable code is a second priority, this time.
Wiriting fast code is a far-away third priority.

=== Oveview ===

All source code lives in the `src` directory.
This solution contains a `main.rs`, which defines the main executable.
There is also a `data.rs`, which specifies data types important for this
solution as well as associated functions, methods, and traits.
There is also an `io.rs`, which contains helper functions related to input
parsing and output processing.

=== Solution ===

Input parsing was a pain.
The idea I used is to split each package at the given commas, but to only use
those commas that are at the correct nesting level.
Then, the parser is called again for each individual entry.
Special care has to be taken since there are empty lists, too.

This time, I did not try to get around self-referencing data types, which means
I got to use `Box<T>` for the first time.
It was nicer than expected.
It's good to know that Rust will ensure memory safety also for data on the heap.

Part 1 was straightforward once the inputs had been parsed.
Luckily, I had decided to create `compare` methods for each separate data type
(`Pkg` and `Elem`) that returned a triplet indicating the ordering.
Thus, in part 2, I could use the very same comparison methods to have Rust sort
the vector of packges.

In order to find out the indices of the divider packages but avoid implementing
a comparison operation for packages, I sorted a vector of tuples that contained
a package and a marker.
Once sorted, I could just retrieve the indices of the markers.

`main.rs`
[source,rust,numbered]
----
include::src/main.rs[tags=main]
----

`data.rs`
[source,rust,numbered]
----
include::src/data.rs[tags=data]
----

There are no tests this time.

=== How to run ===

Please have a look at `src/main.rs` for expeced names of input files.
Assuming the expected files are present, you only need to execute `cargo run` to
run the solution.
The expected input files are ususally called `sample.dat` and `stage_1.dat`.
