== Day 00: Hello World! ==

It'll be the 3rd year of https://www.rust-lang.org/[Rust] solutions for the 2022 edition of 
https://adventofcode.com/2021[Advent of Code]

I created a little solution infrastructure (which resides in the `aoc` subfolder of `day00/rust/mr-kaffee`) I want to use in my solutions.

My day00 solution can be used to

* run all or some of the solutions (`cargo run --release \-- run -y 2022 -d 1..=25` or `cargo run --release \-- run -y 2022 -d 1,3,7` or simply `cargo run --release` to run everything)
* init new days from a template (use batch file `init.bat <day>` or `cargo run --release \-- init ...`)
* submit results (use batch file `submit.bat <day> <part>` or `cargo run --release \-- submit ...`)

Other than that, my challenges are again to create solutions that perform well and that do not use external dependencies (the latter constraint is not applied for the Day 0 Hello World Example, which I also use to run all my solutions in a row).

=== Run solutions for several days ===

=== General structure ===

My solutions will be implemented in a `src/lib.rs` file and generally have the structure detailed below. This is most probably a bit of an overhead, but fun to write and a learning opportunity for me.

==== The Puzzle definition ====

This is a function returning a `mr_kaffee_aoc::Puzzle` struct which defines metadata, input data, references to solver functions and expected solutions.

[source,rust,numbered]
----
include::src/lib.rs[tags=definition]
----


==== Data Structures ====

This includes the code to parse the input data

[source,rust,numbered]
----
include::src/lib.rs[tags=data-structures]
----


==== The solver functions ====

The main solver functions plus potentially helper functions

[source,rust,numbered]
----
include::src/lib.rs[tags=solution]
----


==== Tests ====

Tests, in particular code to execute the test cases typically defined in the puzzles

[source,rust,numbered]
----
include::src/lib.rs[tags=tests]
----
