== Day 8: Treetop Tree House ==

https://rust-lang.org[Rust] solution to https://adventofcode.com/2022/day/8[AoC|2022|8].

I took a moment to put my brain in the condition to think in the 2D grid...

=== Input ===

I directly use the bytes from the input. I scan for the first occurrence of a line break. Its index is the width of the grid. The `PuzzleData` struct's implementation has an additional field for the `height` of the grid.

[source,rust,numbered]
----
include::src/lib.rs[tags=input]
----

=== Star 1 ===

The function `is_visible` verifies in all four directions (left, right, top, bottom), that all trees up to the boundary are smaller. It stops after one such direction is found. 

[source,rust,numbered]
----
include::src/lib.rs[tags=is_visible]
----

Then I count in the `star_1` function, how many trees are visible. For a tree on the boundary, `is_visible` always returns true, so no need to handle the boundary separately.

[source,rust,numbered]
----
include::src/lib.rs[tags=star_1]
----

=== Star 2 ===

Similar to star 1. This time, I use the function `scenic_score` to calculate the scenic score of each tree and the function `star_2` to find the maximum.

In the scenic score calculations, different to the visibility check, the traversal order matters. For left and top directions, the direction is reversed.

[source,rust,numbered]
----
include::src/lib.rs[tags=scenic_score]
----

[source,rust,numbered]
----
include::src/lib.rs[tags=star_2]
----

=== Tests ===

Tests for `star_1`, `scenic_score` and `star_2` functions based on example defined in puzzle description.

[source,rust,numbered]
----
include::src/lib.rs[tags=tests]
----
